# Generated by Django 6.1 on 2026-08-12 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceStream",
            fields=[
                (
                    "stream_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("stream_name", models.CharField(max_length=128)),
                ("detail", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "region_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("region_name", models.CharField(max_length=128)),
                ("in_scope", models.BooleanField(default=False)),
                (
                    "roster_status",
                    models.CharField(default="UNCONFIRMED", max_length=32),
                ),
                ("scope_note", models.TextField(blank=True)),
                ("councils", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["region_name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("allow_unassessed", models.BooleanField(default=True)),
                ("require_triangulation", models.BooleanField(default=True)),
                ("block_unconfirmed_roster", models.BooleanField(default=True)),
                ("active_regions", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationItem",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("issue", models.TextField()),
                ("source_a", models.TextField(blank=True)),
                ("source_b", models.TextField(blank=True)),
                ("why_it_matters", models.TextField(blank=True)),
                ("required_action", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "result_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("result_name", models.CharField(max_length=255)),
                ("intent", models.TextField(blank=True)),
                ("indicators", models.TextField(blank=True)),
                ("project_target", models.TextField(blank=True)),
                ("check_in_field", models.TextField(blank=True)),
                ("evidence_to_request", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammeWorkbook",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="programme",
                        serialize=False,
                        to="assessment.region",
                    ),
                ),
                ("baseline", models.JSONField(blank=True, default=dict)),
                ("activities", models.JSONField(blank=True, default=dict)),
                ("dac", models.JSONField(blank=True, default=dict)),
                ("stakeholders", models.JSONField(blank=True, default=dict)),
                ("sustainability", models.JSONField(blank=True, default=dict)),
                ("learning", models.JSONField(blank=True, default=dict)),
                ("vfm", models.JSONField(blank=True, default=dict)),
                ("data_quality", models.JSONField(blank=True, default=list)),
                ("evidence_map", models.JSONField(blank=True, default=list)),
                ("team_leader_summary", models.JSONField(blank=True, default=dict)),
                ("deliverables", models.JSONField(blank=True, default=dict)),
                ("gates", models.JSONField(blank=True, default=dict)),
                ("history", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "school_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("name_variant", models.CharField(blank=True, max_length=255)),
                ("council", models.CharField(blank=True, max_length=255)),
                ("ward", models.CharField(blank=True, max_length=255)),
                ("roster_status", models.CharField(default="CONFIRMED", max_length=32)),
                ("pupils", models.IntegerField(blank=True, null=True)),
                (
                    "learners_with_disabilities",
                    models.IntegerField(blank=True, null=True),
                ),
                ("disability_categories", models.TextField(blank=True)),
                ("audit_headline", models.TextField(blank=True)),
                ("audit_baseline", models.TextField(blank=True)),
                ("planned_modification", models.TextField(blank=True)),
                ("assessment_focus", models.TextField(blank=True)),
                ("priority", models.CharField(blank=True, max_length=64)),
                ("retest_areas", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="assessment.region",
                    ),
                ),
            ],
            options={
                "ordering": ["school_id"],
            },
        ),
        migrations.CreateModel(
            name="SchoolReport",
            fields=[
                (
                    "report_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("IN PROGRESS", "IN PROGRESS"),
                            ("READY FOR SUBMISSION", "READY FOR SUBMISSION"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("UNDER REVIEW", "UNDER REVIEW"),
                            ("REQUIRES CLARIFICATION", "REQUIRES CLARIFICATION"),
                            ("QA APPROVED", "QA APPROVED"),
                            ("FINALIZED", "FINALIZED"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("visit_start", models.DateField(blank=True, null=True)),
                ("visit_end", models.DateField(blank=True, null=True)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("head_teacher", models.CharField(blank=True, max_length=255)),
                ("focal_person", models.CharField(blank=True, max_length=255)),
                ("school_committee", models.CharField(blank=True, max_length=255)),
                ("teachers_total", models.IntegerField(blank=True, null=True)),
                ("teachers_trained_ie", models.IntegerField(blank=True, null=True)),
                ("learners_total", models.IntegerField(blank=True, null=True)),
                (
                    "learners_with_disabilities",
                    models.IntegerField(blank=True, null=True),
                ),
                ("girls_with_disabilities", models.IntegerField(blank=True, null=True)),
                ("roster_confirmed", models.CharField(blank=True, max_length=64)),
                ("roster_note", models.TextField(blank=True)),
                ("overall_findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("evidence_limitations", models.TextField(blank=True)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("field_questions", models.JSONField(blank=True, default=dict)),
                ("accessibility", models.JSONField(blank=True, default=dict)),
                ("child_journey", models.JSONField(blank=True, default=list)),
                ("interviews", models.JSONField(blank=True, default=list)),
                ("evidence_register", models.JSONField(blank=True, default=list)),
                ("findings", models.JSONField(blank=True, default=list)),
                ("debriefs", models.JSONField(blank=True, default=list)),
                ("history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auditor_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auditor_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "safeguarding_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report",
                        to="assessment.school",
                    ),
                ),
                (
                    "team_leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["report_id"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "evidence_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=512)),
                ("file", models.FileField(blank=True, upload_to="evidence/%Y/%m/")),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("byte_size", models.BigIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("stream_id", models.CharField(blank=True, max_length=32)),
                ("detached", models.BooleanField(default=False)),
                (
                    "sync_status",
                    models.CharField(default="PENDING SYNC", max_length=32),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="assessment.schoolreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "consent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("respondent_code", models.CharField(max_length=64)),
                ("participation_type", models.CharField(max_length=16)),
                ("language", models.CharField(max_length=64)),
                ("adult_status", models.CharField(blank=True, max_length=32)),
                ("caregiver_code", models.CharField(blank=True, max_length=64)),
                ("caregiver_status", models.CharField(blank=True, max_length=32)),
                ("child_assent_status", models.CharField(blank=True, max_length=64)),
                ("photography_consent", models.BooleanField(default=False)),
                ("audio_consent", models.BooleanField(default=False)),
                ("cleared", models.BooleanField(default=False)),
                ("withdrawn", models.BooleanField(default=False)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="assessment.school",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to="assessment.schoolreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "audit_log_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=128)),
                ("field_name", models.CharField(blank=True, max_length=128)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="assessment.schoolreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationQuestion",
            fields=[
                (
                    "question_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("area", models.CharField(max_length=255)),
                ("question", models.TextField()),
                ("planned_standard", models.TextField(blank=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="assessment.result",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationResolution",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="resolution",
                        serialize=False,
                        to="assessment.reconciliationitem",
                    ),
                ),
                ("status", models.CharField(default="OPEN", max_length=32)),
                ("agreed_value", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolAssignment",
            fields=[
                (
                    "assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assignment_role", models.CharField(max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assessment.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "user", "assignment_role")},
            },
        ),
    ]
