# Generated by Django 6.1 on 2026-08-12 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("staff_id", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TEAM_LEADER", "Team Leader / Senior MEL Specialist"),
                            ("AUDITOR", "Inclusive Education Specialist"),
                            ("DISABILITY_INCLUSION", "Disability Inclusion Expert"),
                            ("FINANCE_COMPLIANCE", "Financial and Compliance Auditor"),
                            (
                                "PROCUREMENT",
                                "Procurement and Asset Verification Specialist",
                            ),
                            ("RESEARCH_ASSOCIATE", "Research Associate"),
                            ("DATA_ANALYST", "Data Analyst"),
                            ("SAFEGUARDING_LEAD", "Safeguarding Lead"),
                            ("ADMIN", "System Administrator"),
                            ("CBM_VIEWER", "CBM Viewer"),
                        ],
                        default="AUDITOR",
                        max_length=32,
                    ),
                ),
                ("home_region_id", models.CharField(blank=True, max_length=32)),
                ("must_change_password", models.BooleanField(default=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("session_version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["username"],
            },
        ),
    ]
